name: Build
on: [push,pull_request]
jobs:
  build-openjdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21, 24 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        env:
          DETECTLANGUAGE_API_KEY: ${{ secrets.DETECTLANGUAGE_API_KEY }}
        run: mvn test

  build-oraclejdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-release: [ 21, 24 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-release }}
        uses: oracle-actions/setup-java@v1
        with:
          release: ${{ matrix.java-release }}
      - name: Build with Maven
        env:
          DETECTLANGUAGE_API_KEY: ${{ secrets.DETECTLANGUAGE_API_KEY }}
        run: mvn test
